### ISSUE TITLE
Is there anything special that needs to be done with carthage for the playgrounds to work?

### ISSUE THREAD

**Issue by ghost** [artemnovichkov/UsingPlayground#1]
Hi!

Sorry to be bothering you, but do you maybe happen to know if there is anything special that needs to be done in order for playgrounds to work with frameworks built by carthage?

I've moved from git submodules to carthage in https://github.com/running-away-from/ios-app and my playgrounds stopped working. And then I tried cloning your repo, and they worked! So it gave me some hope and I tried recreating your repo from scratch to find out what I did wrong in my app above but the playgrounds just didn't work ... Here's my attempt: https://github.com/kluufger/UsingPlayground.

The error I keep getting when I compile the `AppFramework` and then run the playground is "couldn't lookup symbols for AppFramework".

**Comment by ghost** [comment]
Actually, once I restart xcode, the playgrounds seem to work for some time ... 
I tagged it just in case to diff against it later: https://github.com/kluufger/UsingPlayground/tree/seems-to-be-working

**Comment by ghost** [comment]
Now it was the opposite.

- Playgrounds are working
- I close xcode
- open it again
- run them again -- get 
```
Playground execution failed:

error: MyPlayground.playground:2:18: error: no such module 'AppFramework'
@testable import AppFramework
```

**Comment by ghost** [comment]
checked out the `seems-to-be-working` tag, same error.

**Comment by ghost** [comment]
I think I'm going slightly insane, just cloned my own repo, checked out `seems-to-be-working` tag, and the playgrounds work there again. But they don't work for the same tag in my other xcode window ...

**Comment by artemnovichkov** [comment]
HI, @kluufger! At first, you should build AppFramework. And then try to run the playground. I guess it's a key point. I have tried to check your project, but the playground runs infinitely 🤦‍♂️

**Comment by ghost** [comment]
👋@artemnovichkov

> At first, you should build AppFramework. And then try to rune the playground.

And I do exactly that, first I build the framework, and only then run the playground. But sometimes it works, and sometimes it doesn't ...

**UPDATE 1:** So strange but just checking out an earlier commit and then checking out master again makes playgrounds work. There must be some kind of trigger during commit checkouts that makes xcode to clean up some erroneous state. Although cleaning up the derived data folder manually does nothing. 

**UPDATE 2:** I've opened a ticket with Apple Developer Technical Support, maybe they would be able to explain why it happens.

**Comment by artemnovichkov** [comment]
Could you please share a ticket link?

**Comment by ghost** [comment]
@artemnovichkov I think these tickets are supposed to be "private":

> THE INFORMATION CONTAINED IN THIS MESSAGE IS UNDER NON-DISCLOSURE

In any way, they replied that this is carthage's problem, and they won't look into it.

I'll try and open an issue on the carthage's repo later today.

**Comment by ghost** [comment]
> I'll try and open an issue on the carthage's repo later today.

@artemnovichkov https://github.com/Carthage/Carthage/issues/2489 

Sorry, got busy for a moment.

**Comment by artemnovichkov** [comment]
No problem, thanks for the information!

**Comment by ghost** [comment]
Hi again!

I've found some kind of resolution for this issue, well, in my particular case, at least: I create a new target which serves as a proxy for playgrounds (just like in this case), but copy `*.xccodeproj` files from `Carthage/Checkouts` there instead of built frameworks by carthage (the app itself still uses the frameworks from `Carthage/Build`). This way playgrounds are quite stable and haven't crashed on me yet.

As a somewhat positive side-effect, it also allowed me to run non-ui tests without launching a simulator via xctool.

**Comment by artemnovichkov** [comment]
Could you please update https://github.com/kluufger/UsingPlayground with this trick?

**Comment by ghost** [comment]
@artemnovichkov sure, here's the relevant commit https://github.com/kluufger/UsingPlayground/commit/e3bc456c76b78b06ceb669918de1373a7762f8ab.

As for the tests, it's a feature of xctool, I think. The command I use (on the framework target) is

```sh
xctool run-tests -test-sdk iphonesimulator11.4 \
  --workspace '<my-workspace>' \
  --scheme '<my-framework>' # although I call these `AppProxy` now, since they just proxy the files in the app for playgrounds and tests
```

Not sure why `-test-sdk iphonesimulator11.4` is needed, but it definetely doesn't start a simulator and the whole command finishes in ~3 seconds for a small project with 17 tests.

```sh
=== RUN-TESTS ===

  [Info] Collecting info for testables... (2379 ms)
    # ** snip **
    17 passed, 0 failed, 0 errored, 17 total (82 ms)


** RUN-TESTS SUCCEEDED: 17 passed, 0 failed, 0 errored, 17 total ** (3589 ms)
```

It's also probably important to set "host" app for the test target to "None" in xcode.
